modLoader = "javafml"
loaderVersion = "[35,)"
license = "MIT"
issueTrackerURL="https://github.com/Waterpicker/ChromaBlocks/issues"

[[mods]]
modId = "chromablocks"
version = "2.0.0"
displayName = "Chroma Blocks"
authors = "Waterpicker"


[[dependencies.chromablocks]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chromablocks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"